import java.util.Dictionary;
import java.util.Hashtable;

public class Database {
    public Database(){

    }

    public Dictionary<String, Move> moveDatabase(){
        Dictionary<String, Move> moveDict = new Hashtable<String, Move>();

        moveDict.put("Heat Wave",
                new Move(
                        95,
                        "Heat Wave",
                        "S",
                        "Fire",
                        "SpA",
                        "SpD",
                        90,
                        new String[]{"No", "No", "No", "No", "No", ///Physical contact, sound type, punch move, biting move, snatchable
                                "No", "No", "Yes", "No", "Yes", /// slicing move, bullet type, wind move, powder move, metronome,
                                "No", "No", "No", "Yes", "Yes"}, ///affected by gravity, defrosts when used, reflected by magic coat/bounce, blocked by protect/detect, copyable by mirror move
                        0,
                        10,
                        "Double",
                        "The user attacks by exhaling hot breath on opposing Pokémon. This may also leave them with a burn.",
                        0.1,
                        0.0417,
                        new String[]{"Burn"},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Ivy Cudgel",
                new Move(
                        100,
                        "Ivy Cudgel",
                        "P",
                        "Grass",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "The user strikes with an ivy-wrapped cudgel. This move's type changes depending on the mask worn by the user, and is has a heightened chance of landing a critical hit.",
                        0,
                        0.125,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Absorb",
                new Move(
                        20,
                        "Absorb",
                        "S",
                        "Grass",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        25,
                        "Single",
                        "A nutrient-draining attack. The user's HP is restored by up to half the damage taken by the target.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{"HP"},
                        0,
                        0.5, ///of damage dealt to target
                        "Damage",
                        1,
                        1
                ));
        moveDict.put("Accelerock",
                new Move(
                        40,
                        "Accelerock",
                        "P",
                        "Rock",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        1,
                        20,
                        "Single",
                        "The user smashes into the target at high speed. This move always goes first.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Acid",
                new Move(
                        40,
                        "Acid",
                        "S",
                        "Poison",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        30,
                        "Double",
                        "Opposing Pokémon are attacked with a spray of harsh acid. This may also lower their Sp. Def stats.",
                        0.1,
                        0.0417,
                        new String[]{""},
                        new String[]{"SpD"},
                        -1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Acid Armor",
                new Move(
                        0,
                        "Acid Armor",
                        "St",
                        "Poison",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        20,
                        "Self",
                        "The user alters its cellular structure to liquify itself, sharply boosting its Defense stat.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{"Def"},
                        2,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Acid Spray",
                new Move(
                        40,
                        "Acid Downpour",
                        "S",
                        "Poison",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "Yes", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user attacks by spitting fluid that works to melt the target. This also harshly lowers the target's Sp. Def stat.",
                        1,
                        0.0417,
                        new String[]{""},
                        new String[]{"SpD"},
                        -2,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Acrobatics",
                new Move(
                        55,
                        "Acrobatics",
                        "P",
                        "Flying",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        15,
                        "Single",
                        "The user nimbly strikes the target. This attack does massive damage if the user isn't holding an item.", ///100% more damage
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Acupressure",
                new Move(
                        0,
                        "Acupressure",
                        "St",
                        "Normal",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        30,
                        "Self or Ally",
                        "The user applies pressure to stress points, sharply boosting one of its allies' stats.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{"Random"},
                        2,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aerial Ace",
                new Move(
                        60,
                        "Aerial Ace",
                        "P",
                        "Flying",
                        "Atk",
                        "Def",
                        101,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "Yes", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user confounds the target with speed, then slashes. This attack never misses.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aeroblast",
                new Move(
                        100,
                        "Aeroblast",
                        "S",
                        "Flying",
                        "SpA",
                        "SpD",
                        95,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        5,
                        "Single",
                        "A vortex of air is shot at the target to inflict damage. This move has a heightened chance of landing a critical hit.",
                        0,
                        0.125,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("After You",
                new Move(
                        0,
                        "After You",
                        "St",
                        "Normal",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No"},
                        0,
                        15,
                        "Single",
                        "The user helps the target and makes it use its move right after the user.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Agility",
                new Move(
                        0,
                        "Agility",
                        "St",
                        "Psychic",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        30,
                        "Self",
                        "The user relaxes and lightens its body to move faster. This sharply boosts its Speed stat.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{"Spe"},
                        2,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Air Cutter",
                new Move(
                        60,
                        "Air Cutter",
                        "S",
                        "Flying",
                        "SpA",
                        "SpD",
                        95,
                        new String[]{"No", "No", "No", "No", "No",
                                "Yes", "No", "Yes", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        25,
                        "Double",
                        "The user launches razor-like wind to slash opposing Pokémon. This move has a heightened chance of landing a critical hit.",
                        0,
                        0.125,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Air Slash",
                new Move(
                        75,
                        "Air Slash",
                        "S",
                        "Flying",
                        "SpA",
                        "SpD",
                        95,
                        new String[]{"No", "No", "No", "No", "No",
                                "Yes", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        15,
                        "Single",
                        "The user attacks with a blade of air that slices even the sky. This may also make the target flinch.",
                        0.3,
                        0.0417,
                        new String[]{"Flinch"},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Alluring Voice",
                new Move(
                        80,
                        "Alluring Voice",
                        "S",
                        "Fairy",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "Yes", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        25,
                        "Single",
                        "The user attacks the target using its angelic voice. This also confuses the target if its stats have been boosted during the turn.",
                        1,
                        0.0417,
                        new String[]{"Confusion"}, ///if stats have been boosted this turn
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Ally Switch",
                new Move(
                        0,
                        "Ally Switch",
                        "St",
                        "Psychic",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        2,
                        15,
                        "Self",
                        "The user teleports using a strange power and switches places with one of its allies. This move's chance of failing rises if it is used in succession.", ///rate of success = (1/3)^use#-1
                        1,
                        0,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Amnesia",
                new Move(
                        0,
                        "Amnesia",
                        "St",
                        "Psychic",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        20,
                        "Self",
                        "The user temporarily empties its mind to forget its concerns. This sharply boosts the user's Sp. Def stat.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{"SpD"},
                        2,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Anchor Shot",
                new Move(
                        80,
                        "Anchor Shot",
                        "P",
                        "Steel",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user entangles the target with its anchor chain while attacking., The target becomes unable to flee.",
                        1,
                        0.0417,
                        new String[]{"Trapped"},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Ancient Power",
                new Move(
                        60,
                        "Ancient Power",
                        "S",
                        "Rock",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        5,
                        "Single",
                        "The user attacks with a prehistoric power. This may also boost all the user's stats at once.",
                        0.1,
                        0.0417,
                        new String[]{""},
                        new String[]{"All"},
                        1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Apple Acid",
                new Move(
                        80,
                        "Apple Acid",
                        "S",
                        "Grass",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "The user attacks the target with an acidic liquid created from tart apples. This also lowers the target's Sp. Def stat.",
                        1,
                        0.0417,
                        new String[]{""},
                        new String[]{"SpD"},
                        -1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aqua Cutter",
                new Move(
                        70,
                        "Aqua Cutter",
                        "P",
                        "Water",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "Yes", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user expels pressurized water to cut at the target like a blade. This move has a heightened chance of landing a critical hit.",
                        0,
                        0.125,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aqua Jet",
                new Move(
                        40,
                        "Aqua Jet",
                        "P",
                        "Water",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        1,
                        20,
                        "Single",
                        "The user lunges at the target to inflict damage, moving at blinding speed. This move always goes first.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aqua Ring",
                new Move(
                        0,
                        "Aqua Ring",
                        "St",
                        "Water",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        20,
                        "Self",
                        "The user envelops itself in a veil made of water. It regains some HP every turn.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0.0625, ///every turn
                        "Turn",
                        1,
                        1
                ));
        moveDict.put("Aqua Step",
                new Move(
                        80,
                        "Aqua Step",
                        "P",
                        "Water",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "The user toys with the target and attacks it using light and fluid dance steps. This also boosts the user's Speed stat.",
                        1,
                        0.0417,
                        new String[]{""},
                        new String[]{"Spe"},
                        1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aqua Tail",
                new Move(
                        90,
                        "Aqua Tail",
                        "P",
                        "Water",
                        "Atk",
                        "Def",
                        90,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "The user attacks by swinging its tail as if it were a vicious wave in a raging storm.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Arm Thrust",
                new Move(
                        15,
                        "Arm Thrust",
                        "P",
                        "Fighting",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user attacks the target with open-palmed arm thrusts. This move hits two to five times in a row.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        2,
                        5 ///37.5% for 2 and 3 hits, 12.5% for 5 and 5 hits
                ));
        moveDict.put("Armor Cannon",
                new Move(
                        120,
                        "Armor Cannon",
                        "S",
                        "Fire",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        5,
                        "Single",
                        "The user shoots its own armor out as blazing projectiles. This also lowers the user's Defense and Sp. Def stats.",
                        1,
                        0.0417,
                        new String[]{""},
                        new String[]{"Def, SpD"},
                        -1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aromatic Mist",
                new Move(
                        0,
                        "Aromatic Mist",
                        "St",
                        "Fairy",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "No"},
                        0,
                        20,
                        "Ally",
                        "The user boosts the Sp. Def stat of an ally Pokémon by using a mysterious aroma.",
                        1,
                        0,
                        new String[]{""},
                        new String[]{"SpD"},
                        1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Assurance",
                new Move(
                        60,
                        "Assurance",
                        "P",
                        "Dark",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "This move's power is doubled if the target has already taken some damage in the same turn.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Astonish",
                new Move(
                        30,
                        "Astonish",
                        "P",
                        "Ghost",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        15,
                        "Single",
                        "The user attacks the target by crying out in a startling fashion. This may also make the target flinch.",
                        0.3,
                        0.0417,
                        new String[]{"Flinch"},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Astral Barrage",
                new Move(
                        120,
                        "Astral Barrage",
                        "S",
                        "Ghost",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        5,
                        "Double",
                        "The user attacks by sending a frightful amount fo small ghosts at opposing Pokémon.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Attack Order",
                new Move(
                        90,
                        "Attack Order",
                        "P",
                        "Bug",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        15,
                        "Single",
                        "The user calls out its underlings to pummel the target. This move has a heightened chance of landing a critical hit.",
                        0,
                        0.125,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Attract",
                new Move(
                        0,
                        "Attract",
                        "St",
                        "Normal",
                        "",
                        "",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "Yes", "Yes", "Yes"},
                        0,
                        15,
                        "Single",
                        "If the target is of the opposite gender to the user, it becomes infatuated with the user and will sometimes be unable to use its moves.",
                        1,
                        0,
                        new String[]{"Infatuation"}, ///sometimes prohibits the infatuated from using its moves
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aura Sphere",
                new Move(
                        80,
                        "Aura Sphere",
                        "S",
                        "Fighting",
                        "SpA",
                        "SpD",
                        101,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "Yes", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The user lets loose a pulse of aura power from deep within its body at the target. This attack never misses.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aura Wheel",
                new Move(
                        110,
                        "Aura Wheel",
                        "P",
                        "Electric", ///dark if Morpeko is Hangry
                        "Atk",
                        "Def",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "No",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "Morpeko attacks and boosts its Speed stat with the energy stored in its cheeks. This move's type changes depending on the user's form.",
                        1,
                        0.0417,
                        new String[]{""},
                        new String[]{"Spe"},
                        1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aurora Beam",
                new Move(
                        65,
                        "Aurora Beam",
                        "S",
                        "Ice",
                        "SpA",
                        "SpD",
                        100,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        20,
                        "Single",
                        "The target is hit with a rainbow-colored beam. This may also lower the target's Attack stat.",
                        0.1,
                        0.0417,
                        new String[]{""},
                        new String[]{"Atk"},
                        -1,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Aurora Veil",
                new Move(
                        0,
                        "Aurora Veil",
                        "St",
                        "Ice",
                        "",
                        "",
                        101,
                        new String[]{"No", "No", "No", "No", "Yes",
                                "No", "No", "No", "No", "Yes",
                                    "No", "No", "No", "No", "No"},
                        0,
                        20,
                        "Ally",
                        "This move reduces damage from physical and special moves for five turns. This can be used only when it is snowing.",
                        0,
                        0,
                        new String[]{"Aurora Veil"},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Avalanche",
                new Move(
                        60,
                        "Avalanche",
                        "P",
                        "Ice",
                        "Atk",
                        "Def",
                        100,
                        new String[]{"Yes", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        -4,
                        10,
                        "Single",
                        "This move's power is double if the target has inflicted damage on the user in the same.",
                        0,
                        0.0417,
                        new String[]{""},
                        new String[]{""},
                        0,
                        0,
                        "",
                        1,
                        1
                ));
        moveDict.put("Axe Kick",
                new Move(
                        120,
                        "Axe Kick",
                        "P",
                        "Fighting",
                        "Atk",
                        "Def",
                        90,
                        new String[]{"No", "No", "No", "No", "No",
                                "No", "No", "No", "No", "Yes",
                                "No", "No", "No", "Yes", "Yes"},
                        0,
                        10,
                        "Single",
                        "The user attacks by kicking up into the air and slamming its heel down upon the target. This may also confuse the target. If it missed, the user takes damage instead.",
                        0.3,
                        0.0417,
                        new String[]{"Confusion"},
                        new String[]{""},
                        0,
                        -.5,
                        "Miss",
                        1,
                        1
                ));
        return moveDict;
    }
}
